### ISSUE TITLE
fix: using 'Custom SSH Host Keys' on a windows host throws 'permissions are too open'

### ISSUE THREAD

**Issue by BePo65** [rockstorm101/git-server-docker#10]
I am using git-server-docker on a windows host.
On activating the feature 'Custom SSH Host Keys' from the [documentation](https://github.com/rockstorm101/git-server-docker#custom-ssh-host-keys) I get the following log entries (`ssh_host_rsa_key` being the new key):

```
/docker-entrypoint.sh: Starting container configuration
/docker-entrypoint.sh: Running /docker-entrypoint.d/10-setup.sh
/docker-entrypoint.sh: Container configuration completed
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/etc/ssh/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

That is no surprise, as permissions from windows 'volumes' cannot be transferred to a unix environment.

The solution would be, to add the following line after line 79 in the `10-setup.sh` file:
```
chmod -R 600 ssh_host_*
```

Should I create a pr for that?

**Comment by rockstorm101** [comment]
Hi @BePo65, thanks for reporting the issue. I confirm I can reproduce it. No need for a PR, it seems trivial to fix.
