### ISSUE TITLE
SSH connection denied

### ISSUE THREAD

**Issue by pcouas** [rockstorm101/git-server-docker#3]
Hi

I have donwloaded your docker file and container running
A
docker build -t igits5 .
docker run --detach --name cgits5 --publish 2223:22 --volume /c/Users/COUAS/git-server5/repos:/srv/git --volume /c/Users/COUAS/git-server5/keys:/home/git/.ssh/authorized_keys -t -i igits5

B I have created my ssh key from Windows 10 like
ssh-keygen -o -t rsa -f Z:\zpoubelle\tssh4\id_rsa -C git -N ""

C i have copy my pub on /c/Users/COUAS/git-server5/keys

D i restart ans try
ssh git@127.0.0.1 -v -p 2223 -i Z:\zpoubelle\tssh4\id_rsa
C:\Users\COUAS>ssh git@127.0.0.1 -v -p 2223 -i Z:\zpoubelle\tssh4\id_rsa
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2223.
debug1: Connection established.
debug1: identity file Z:\\zpoubelle\\tssh4\\id_rsa type 0
debug1: identity file Z:\\zpoubelle\\tssh4\\id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3
debug1: match: OpenSSH_8.9p1 Ubuntu-3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 127.0.0.1:2223 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:6IAdnOT8Yls3VGOKVKaRjFNGHt/RLWH9eoakalMIDhk
debug1: Host '[127.0.0.1]:2223' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\COUAS/.ssh/known_hosts:4
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: Z:\\zpoubelle\\tssh4\\id_rsa RSA SHA256:mez7LdYFtFbO4ZiHutlanL+vxpNzKqum2SU/zQX4CLQ explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com (unrecognised)
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: Z:\\zpoubelle\\tssh4\\id_rsa RSA SHA256:mez7LdYFtFbO4ZiHutlanL+vxpNzKqum2SU/zQX4CLQ explicit
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
git@127.0.0.1: Permission denied (publickey).

do you have an idea ?
My pub key is copied on /home/git/.ssh/authorized_keys with -rwxrwxrwx 1 root root  558 Oct  2 07:58 id_rsa.pub
I have many doubt here !
i have tried too to move id_rsa.pub on file /home/git//ssh/authorized_keys not directory with chown git and chmod 600 without best result
I have an Windows10 computer

Regards

**Comment by rockstorm101** [comment]
What was the solution in the end? Now I'm curious I couldn't spot anything wrong in your config.
