### ISSUE TITLE
git connection over ssh not possible

### ISSUE THREAD

**Issue by pcouas** [rockstorm101/git-server-docker#4]
Hi

I could connect via ssh from my windows10 PC to docker with command ssh git@127.0.0.1 -v -p 2223 -i Z:\zpoubelle\tssh4\id_rsa
But i could not git clone with command
set GIT_SSH_COMMAND="ssh -p 2223 -i Z:\zpoubelle\tssh4\id_rsa"
git clone git@127.0.0.1:2223/srv/git/your-repo.git --verbose

output is :
"ssh -p2223 -i Z:\zpoubelle\tssh4\id_rsa": line 1: ssh -p 2223 -i Z:\zpoubelle\tssh4\id_rsa: No such file or directory
fatal: Could not read from remote repository.

I have tried too set GIT_SSH_COMMAND="ssh -p 2223-i /z/zpoubelle/tssh4/id_rsa" without succes

On docker i have
drwxr-xr-x 1 root root 4096 Oct  2 17:17 ..
drwxr-xr-x 1 git  git   512 Oct  1 17:42 your-repo.git
drwxr-xr-x 1 git  git   512 Oct  1 17:42 .
pwd
/srv/git

**Comment by rockstorm101** [comment]
Does it make any difference if you use it as a one liner:
```
set GIT_SSH_COMMAND=ssh -i Z:\zpoubelle\tssh4\id_rsa & git clone git@127.0.0.1:2223/srv/git/your-repo.git
```

Or probably cleaner and more reusable, try using a config file at `C:\Users\[User]\.ssh\config` with something like this:
```
Host local
    HostName     = 127.0.0.1
    User         = git
    Port         = 2223
    IdentityFile = Z:\zpoubelle\tssh4\id_rsa
```
Then you should be able to clone like:
```git clone local:/srv/git/your-repo.git```

`your-repo.git` is inside `/srv/git` folder, right?

**Comment by rockstorm101** [comment]
This is an old issue so I'll assume the issue is now resolved. Otherwise, please don't hesitate to reopen this.
