### ISSUE TITLE
Problems using server

### ISSUE THREAD

**Issue by xxlbug** [rockstorm101/git-server-docker#7]
Hello again ;-)

now my server is up an running and i can connect. BUT i can't clone any repos. In essence i think i overlooked something obvious with my tinkering and need some help please.

The current setup:
- Unraid
- Docker Compose
- user/group with ids 99/100 and all folders are tripple checked for rights
- docker folder for service with all static files
- appdata folder for service with ssh config folder, sshd_config and ssh_host_keys folder
- separate folder for repos

The service is up an running but a login with the git user gives me (`ssh git@git-server -p 22`):
```
fatal: could not open '/dev/null' for reading and writing: Permission denied
Connection to git-server closed.
```

In the enhanced logs/debug mode i get:
```
15/01/2023 21:43:42 Accepted publickey for git from 10.0.1.28 port 55336 ssh2: RSA SHA256:xxxx
15/01/2023 21:43:42 Received disconnect from 10.0.1.28 port 55336:11: disconnected by user
15/01/2023 21:43:42 Disconnected from user git 10.0.1.28 port 55336
```

I tried going directly into the docker shell and create a repo to clone it but get a similar error with git clone:
```
git clone ssh://git@10.0.2.28:22/xNotes.git
Cloning into 'xNotes'...
fatal: could not open '/dev/null' for reading and writing: Permission denied
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Not sure how to proceed, any logs i can provide i will.

Thank you kindly

**Comment by rockstorm101** [comment]
Hi @xxlbug, thanks for reporting back. I've been able to reproduce this behavior. I suspect I missed the `-H` option on the script I provided on [this answer][1]. (Which again proves that fiddling with system users must be done very carefully) Please change it as follows and let us know if you can now log in and clone repositories. 

```diff
- adduser -u 405 -G users -h /dev/null -g 'guest' -S guest
+ adduser -u 405 -G users -H -h /dev/null -g 'guest' -S guest
```

[1]: https://github.com/rockstorm101/git-server-docker/issues/6#issuecomment-1377463700

**Comment by xxlbug** [comment]
Thank you very much, now it works as intended :-)
