### ISSUE TITLE
Instructions about disabling interactive login are incorrect

### ISSUE THREAD

**Issue by nestor013** [rockstorm101/git-server-docker#8]
According to section **Disable Git User Interactive Login**  I tried to mount an executable (empty sh script). I got a 
`git-server  | chown: /home/git/git-shell-commands/no-interactive-login: Read-only file system`

Apparently the error comes from the `:ro` in the corresponding volume instruction. If removing it, all work fine.
Hope it could help.

**Comment by rockstorm101** [comment]
You are very right, good catch. Thanks for reaching out.
