### ISSUE TITLE
allow to disable password auth via environment variable

### ISSUE THREAD

**Issue by prabirshrestha** [rockstorm101/git-server-docker#9]
Right now we need to override the entire `sshd_config` to disable password auth.

Is it possible instead have an option to pass an environment variable to disable `PasswordAuth` `-e SSH_PASSWORD_AUTH=no`. Whenever the server docker image starts if the environment variable is set, it can override `#PasswordAuthentication yes`.

Might be with something like this?

```bash
sed -i "s/.*PasswordAuthentication.*/PasswordAuthentication no/g" /etc/ssh/sshd_config
```

**Comment by rockstorm101** [comment]
Hi @prabirshrestha, thanks for your suggestion. I'm looking into it.

**Comment by prabirshrestha** [comment]
Would be good to also support `-e SSH_PUBLIC_KEY_URL=https://github.com/username.keys`. This would allow to have auth based on single docker command.

```bash
docker run --detach \
  --name git-server \
  --volume git-repositories:/srv/git \
  --env SSH_PASSWORD_AUTH=no \
  --env SSH_PUBLIC_KEY_URL=https://github.com/username.keys \
  --publish 2222:22 \
  rockstorm/git-server
```

or you could also detect `http://` and `https://` in `SSH_HOST_KEYS_PATH` if you want to reuse the name.

```
SSH_HOST_KEYS_PATH: /tmp/host-keys
```
